In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Import the numpy, matplotlib and pandas libraries to work with arrays,
visualization and matrices, respectively

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import the dataset and create two vectors

In [3]:
dataset = pd.read_csv('/content/drive/My Drive/XGBoost/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Split into training and testing sets for independent and dependent variables

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state=0)

Create an instance of the XG Boost classifier, then pass the X_train and y_train values in its fit function.

In [5]:
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier()
y_train = (y_train - 2) / 2
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

Generate the confusion matrix to display true and false positives/negatives. Then calculate the accuracy_score using y_test and y_pred.

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = xgb_classifier.predict(X_test)
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)
accuracy_score(y_test, y_pred)

[[  0   0   0   0]
 [  0   0   0   0]
 [103   4   0   0]
 [  6  58   0   0]]


0.0

Import cross_val_score from the sklearn.model_selection library to handle K Fold Cross Validation. Specify the estimator parameter to be the XGBoost model. Next specify the X and y parameters to be the X_train and y_train values, respectively, for applying cross validation. Finally specify the cv to be 10, which means 10 different models will be created. Lastly, calculate the mean and standard deviation of the accuracies of these models, and print them out.

In [7]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = xgb_classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.67 %
Standard Deviation: 2.78 %
